# 基于streamlit的机器学习应用开发

In [2]:
import streamlit as st 
import numpy as np 
import pandas as pd
import pickle

import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score,confusion_matrix,f1_score

## 机器学习应用的基本流程

1.数据导入 2.数据处理 3.选择模型 4.模型拟合 5.学习效果 6. 模型的使用

* 请在streamlit中实现如下机器学习流程（参数与模型可选）

### 数据导入

In [3]:
data = datasets.load_iris()
#data = datasets.load_wine()
#data = datasets.load_breast_cancer()

In [4]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 数据分析与处理

In [47]:
df_data=pd.DataFrame(data.data,columns=data.feature_names)

In [49]:
df_target=pd.Series(data.target)
df_target.name="class"

In [51]:
pd.concat([df_data,df_target],axis=1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [62]:
#data

In [13]:
x = data.data
y = data.target

NameError: name 'data' is not defined

In [14]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### 模型的拟合

In [37]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
                                                    #, random_state=1234)

In [38]:
model=RandomForestClassifier(n_estimators=50,max_depth=3, random_state=1234)
#model=SVC(C=2)
#model = KNeighborsClassifier(n_neighbors=4)

In [39]:
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, n_estimators=50, random_state=1234)

In [64]:
#X_test

### 模型的验证

In [40]:
y_pred = model.predict(X_test)

In [19]:
acc = accuracy_score(y_test, y_pred)

In [41]:
confusion_matrix(y_test, y_pred)

array([[2986,    0],
       [   4,    7]], dtype=int64)

In [43]:
f1_score(y_test, y_pred)

0.7777777777777778

In [20]:
acc

0.9994994994994995

### 模型的使用

In [57]:
model.predict([[4.8, 3.4, 1.6, 0.2]])

array([0])

In [61]:
model.feature_importances_

array([0.06728234, 0.01665775, 0.48895537, 0.42710455])

In [44]:
#enc.fit(pd["Technology"].values)

## 精准营销应用搭建

* 定向营销

根据过去对目标营销活动的响应创建客户响应模型，以预测可能响应的客户并提高新活动的转化率。

### 数据导入

In [3]:
df=pd.read_csv(r"F:\notebooks1\streamlit\data\old.csv")

In [3]:
#从过去的营销活动中加载和准备数据，包括接收者属性（例如年龄、性别、地区）和行为属性（产品和服务的使用、网站等）。
df.head()

Name  Age  Gender   Area    Email Mobile  Logins 4 weeks  \
0       COX   64  female  urban     free  never               1   
1    FARLEY   49    male  urban  premium  never               0   
2      HYDE   63    male  urban     free  never               0   
3  SANTIAGO   75    male  urban  premium    yes               0   
4  COPELAND   37  female  urban     free    yes               0   

   Logins 6 months  Sales 4 weeks  Sales 6 months  Sales total Response  
0                1              0               0            0       no  
1                4              0               0            0      yes  
2                0              0               0            0       no  
3                0              0               0            0      yes  
4                0              0               0           62       no

### 数据分析与处理

https://blog.csdn.net/qq_55342245/article/details/121673329

### classwork 2

1. 完成数据的读入
2. 完成数据的处理，得到特征矩阵x与目标向量y

In [3]:
df["Response"]=df["Response"].map({"no":0,"yes":1})

In [4]:
df.drop(axis=1,columns="Name",inplace=True)

In [8]:
df.head()

Age  Gender   Area    Email Mobile  Logins 4 weeks  Logins 6 months  \
0   64  female  urban     free  never               1                1   
1   49    male  urban  premium  never               0                4   
2   63    male  urban     free  never               0                0   
3   75    male  urban  premium    yes               0                0   
4   37  female  urban     free    yes               0                0   

   Sales 4 weeks  Sales 6 months  Sales total  Response  
0              0               0            0         0  
1              0               0            0         1  
2              0               0            0         0  
3              0               0            0         1  
4              0               0           62         0

In [24]:
s=pd.Series(list('abcd'))
s_=pd.get_dummies(s)
print(s_)

   a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1


In [5]:
df_0=pd.get_dummies(df,columns=["Gender","Area","Email","Mobile"])

In [10]:
df_0.head()

Age  Logins 4 weeks  Logins 6 months  Sales 4 weeks  Sales 6 months  \
0   64               1                1              0               0   
1   49               0                4              0               0   
2   63               0                0              0               0   
3   75               0                0              0               0   
4   37               0                0              0               0   

   Sales total  Response  Gender_female  Gender_male  Area_rural  Area_urban  \
0            0         0              1            0           0           1   
1            0         1              0            1           0           1   
2            0         0              0            1           0           1   
3            0         1              0            1           0           1   
4           62         0              1            0           0           1   

   Email_free  Email_premium  Mobile_always  Mobile_never  Mobile_yes  
0           1              0              0             1           0  
1           0              1              0             1           0  
2           1              0              0             1           0  
3           0              1              0             0           1  
4           1              0              0             0           1

In [6]:
y=df_0["Response"].values

In [7]:
x=df_0.drop(axis=1,columns="Response").values

### 模型的拟合与验证

In [8]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
model=RandomForestClassifier(n_estimators=10,max_depth=2, random_state=1234)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
f1_score(y_test, y_pred)

0.7172413793103448

### 模型的使用

In [9]:
df_new=pd.read_csv(r"F:\notebooks1\streamlit\data\new.csv")

In [10]:
df_new.drop(axis=1,columns="Name",inplace=True)

In [11]:
df_new=pd.get_dummies(df_new,columns=["Gender","Area","Email","Mobile"])

In [32]:
df_new.head()

Age  Logins 4 weeks  Logins 6 months  Sales 4 weeks  Sales 6 months  \
0   54               0                7              0               0   
1   88               3                3              0               0   
2   31               0                7              0               0   
3   54               0                0              0               0   
4   25               0                0              0               0   

   Sales total  Gender_female  Gender_male  Area_rural  Area_urban  \
0            0              1            0           1           0   
1            0              0            1           0           1   
2            0              1            0           0           1   
3            0              1            0           1           0   
4            0              0            1           0           1   

   Email_free  Email_premium  Mobile_always  Mobile_never  Mobile_yes  
0           1              0              1             0           0  
1           1              0              0             1           0  
2           1              0              1             0           0  
3           1              0              0             1           0  
4           1              0              0             1           0

In [12]:
y_pred = model.predict(df_new.values)

In [13]:
df_new["predict"]=y_pred

In [14]:
df_new

Age  Logins 4 weeks  Logins 6 months  Sales 4 weeks  Sales 6 months  \
0     54               0                7              0               0   
1     88               3                3              0               0   
2     31               0                7              0               0   
3     54               0                0              0               0   
4     25               0                0              0               0   
..   ...             ...              ...            ...             ...   
995   51               5                5              0               0   
996   35               3               10             46             131   
997   81               0                0              0               0   
998   27               9                9              0               0   
999   19               2                2              0               0   

     Sales total  Gender_female  Gender_male  Area_rural  Area_urban  \
0              0              1            0           1           0   
1              0              0            1           0           1   
2              0              1            0           0           1   
3              0              1            0           1           0   
4              0              0            1           0           1   
..           ...            ...          ...         ...         ...   
995            0              1            0           0           1   
996          131              0            1           0           1   
997          366              1            0           1           0   
998            0              0            1           1           0   
999            0              0            1           1           0   

     Email_free  Email_premium  Mobile_always  Mobile_never  Mobile_yes  \
0             1              0              1             0           0   
1             1              0              0             1           0   
2             1              0              1             0           0   
3             1              0              0             1           0   
4             1              0              0             1           0   
..          ...            ...            ...           ...         ...   
995           1              0              0             1           0   
996           1              0              0             1           0   
997           1              0              0             1           0   
998           1              0              0             1           0   
999           1              0              1             0           0   

     predict  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
995        0  
996        1  
997        0  
998        1  
999        0  

[1000 rows x 16 columns]

In [17]:
help(df_new.style)

Help on Styler in module pandas.io.formats.style object:

class Styler(pandas.io.formats.style_render.StylerRenderer)
 |  Styler(data: 'DataFrame | Series', precision: 'int | None' = None, table_styles: 'CSSStyles | None' = None, uuid: 'str | None' = None, caption: 'str | tuple | None' = None, table_attributes: 'str | None' = None, cell_ids: 'bool' = True, na_rep: 'str | None' = None, uuid_len: 'int' = 5, decimal: 'str | None' = None, thousands: 'str | None' = None, escape: 'str | None' = None, formatter: 'ExtFormatter | None' = None)
 |  
 |  Helps style a DataFrame or Series according to the data with HTML and CSS.
 |  
 |  Parameters
 |  ----------
 |  data : Series or DataFrame
 |      Data to be styled - either a Series or DataFrame.
 |  precision : int, optional
 |      Precision to round floats to. If not given defaults to
 |      ``pandas.options.styler.format.precision``.
 |  
 |      .. versionchanged:: 1.4.0
 |  table_styles : list-like, default None
 |      List of {selecto

### 在streamlit 中实现上面代码并实现模型参数的调节功能-classwork3

https://docs.streamlit.io/library/api-reference/control-flow/st.form

In [ ]:
import streamlit as st

with st.form("my_form"):
   st.write("Inside the form")
   slider_val = st.slider("Form slider")
   checkbox_val = st.checkbox("Form checkbox")

   # Every form must have a submit button.
   submitted = st.form_submit_button("Submit")
   if submitted:
       st.write("slider", slider_val, "checkbox", checkbox_val)

st.write("Outside the form")

### 构建分页应用-classwork4

* 第一页分析数据训练模型

* 第二页使用模型，通过session state实现分页共享变量

https://docs.streamlit.io/library/get-started/main-concepts

https://docs.streamlit.io/library/api-reference/session-state

In [ ]:
# Initialization
if 'key' not in st.session_state:
    st.session_state['key'] = 'value'

# Session State also supports attribute based syntax
if 'key' not in st.session_state:
    st.session_state.key = 'value'

### 实现模型与数据的本地导入与保存-classwork5

https://docs.streamlit.io/library/api-reference/widgets/st.download_button

* 实现新数据通过本地文件导入

* 实现按钮控制模型导出到本地

* 实现模型通过本地文件导入

In [ ]:
import streamlit as st
import pandas as pd
from io import StringIO

uploaded_file = st.file_uploader("Choose a file")
if uploaded_file is not None:
    # To read file as bytes:
    bytes_data = uploaded_file.getvalue()
    st.write(bytes_data)

    # To convert to a string based IO:
    stringio = StringIO(uploaded_file.getvalue().decode("utf-8"))
    st.write(stringio)

    # To read file as string:
    string_data = stringio.read()
    st.write(string_data)

    # Can be used wherever a "file-like" object is accepted:
    dataframe = pd.read_csv(uploaded_file)
    st.write(dataframe)

In [1]:
import pickle

In [14]:
pkl_filename = "F:\\pickle_model.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(model, file)

In [15]:
# Load from file
with open(pkl_filename, 'rb') as file:
    pickle_model = pickle.load(file)

### 在模型训练页加入透视表分析,并通过表单控制表的维度

In [24]:
#help(df.pivot_table)

In [4]:
df.columns

Index(['Name', 'Age', 'Gender', 'Area', 'Email', 'Mobile', 'Logins 4 weeks',
       'Logins 6 months', 'Sales 4 weeks', 'Sales 6 months', 'Sales total',
       'Response'],
      dtype='object')

In [6]:
df.head()

Name  Age  Gender   Area    Email Mobile  Logins 4 weeks  \
0       COX   64  female  urban     free  never               1   
1    FARLEY   49    male  urban  premium  never               0   
2      HYDE   63    male  urban     free  never               0   
3  SANTIAGO   75    male  urban  premium    yes               0   
4  COPELAND   37  female  urban     free    yes               0   

   Logins 6 months  Sales 4 weeks  Sales 6 months  Sales total Response  
0                1              0               0            0       no  
1                4              0               0            0      yes  
2                0              0               0            0       no  
3                0              0               0            0      yes  
4                0              0               0           62       no

In [ ]:
pivot

In [16]:
df.pivot_table(index=["Response","Gender"],aggfunc=[np.mean])

mean                                               \
                       Age Logins 4 weeks Logins 6 months Sales 4 weeks   
Response Gender                                                           
no       female  46.807190       0.375817        1.928105      0.000000   
         male    47.232000       0.196000        1.360000      0.000000   
yes      female  45.901316       4.296053        8.098684     10.677632   
         male    46.030822       2.732877        4.852740      7.421233   

                                            
                Sales 6 months Sales total  
Response Gender                             
no       female       3.738562   14.539216  
         male         2.140000   16.384000  
yes      female      35.276316   58.250000  
         male        25.801370   39.654110

In [27]:
df.pivot_table(index="Response")

Age  Logins 4 weeks  Logins 6 months  Sales 4 weeks  \
Response                                                              
no        46.998201        0.294964         1.672662       0.000000   
yes       45.986486        3.268018         5.963964       8.536036   

          Sales 6 months  Sales total  
Response                               
no              3.019784    15.368705  
yes            29.045045    46.020270

In [17]:
z1=df.pivot_table(index=["Response","Gender"],aggfunc=[np.mean])
z1

mean                                               \
                       Age Logins 4 weeks Logins 6 months Sales 4 weeks   
Response Gender                                                           
no       female  46.807190       0.375817        1.928105      0.000000   
         male    47.232000       0.196000        1.360000      0.000000   
yes      female  45.901316       4.296053        8.098684     10.677632   
         male    46.030822       2.732877        4.852740      7.421233   

                                            
                Sales 6 months Sales total  
Response Gender                             
no       female       3.738562   14.539216  
         male         2.140000   16.384000  
yes      female      35.276316   58.250000  
         male        25.801370   39.654110

In [39]:
z1.index.tolist()

[('no', 'female'), ('no', 'male'), ('yes', 'female'), ('yes', 'male')]

### 对透视表分析进行可视化

In [25]:
for i in z1.columns:
    print("_".join(i))

mean_Age
mean_Logins 4 weeks
mean_Logins 6 months
mean_Sales 4 weeks
mean_Sales 6 months
mean_Sales total


In [26]:
["_".join(i) for i in z1.columns]

['mean_Age',
 'mean_Logins 4 weeks',
 'mean_Logins 6 months',
 'mean_Sales 4 weeks',
 'mean_Sales 6 months',
 'mean_Sales total']

In [32]:
isinstance(z1.columns[0], tuple)

True

In [34]:
z1.columns[0]

('mean', 'Age')

In [33]:
isinstance(z1.index[0], tuple)

True

In [31]:
type(z1.columns[0])

tuple

In [12]:
for i in z1.index:
    print(i[0]+"-"+i[1])

no-female
no-male
yes-female
yes-male


In [18]:
print(type(z1.index[0]))

<class 'tuple'>


In [9]:
z1.columns

MultiIndex([('mean',             'Age'),
            ('mean',  'Logins 4 weeks'),
            ('mean', 'Logins 6 months'),
            ('mean',   'Sales 4 weeks'),
            ('mean',  'Sales 6 months'),
            ('mean',     'Sales total')],
           )

In [21]:
[ "-".join(i) for i in z1.columns]

['mean-Age',
 'mean-Logins 4 weeks',
 'mean-Logins 6 months',
 'mean-Sales 4 weeks',
 'mean-Sales 6 months',
 'mean-Sales total']

In [37]:
np.__version__

'1.22.4'

In [35]:
z1.columns

MultiIndex([('mean',             'Age'),
            ('mean',  'Logins 4 weeks'),
            ('mean', 'Logins 6 months'),
            ('mean',   'Sales 4 weeks'),
            ('mean',  'Sales 6 months'),
            ('mean',     'Sales total')],
           )

In [24]:
z1.iloc[:,0].tolist()

[46.80718954248366, 47.232, 45.901315789473685, 46.03082191780822]

## 用户流失预警系统的搭建

* 流失用户的定义

* 样本不平衡问题

In [19]:
df=pd.read_csv(r"F:\notebooks1\streamlit\data\aaa.csv",parse_dates=["CustomerSince"])

In [20]:
df.head()

Technology  Age       CustomerSince  SupportCallsLastYear  AverageBill  \
0         4G    1 2013-06-06 22:27:16                     1           71   
1      phone   46 2011-10-05 22:27:16                     0           88   
2         4G   47 2012-07-24 22:27:16                     1           80   
3      phone   43 2010-08-31 22:27:16                     1           64   
4      fiber   37 2011-07-24 22:27:16                     2          105   

   ChurnIndicator  
0           0.013  
1           0.006  
2           0.016  
3           0.021  
4           0.032

In [21]:
def com_bi(x):
    if x>0.4:
        return 1
    else:
        return 0

In [22]:
df["ChurnIndicator"]=df["ChurnIndicator"].map(com_bi)

In [23]:
df=pd.get_dummies(df,columns=["Technology"])

In [25]:
#df[df["ChurnIndicator"]==1]

In [26]:
(df["CustomerSince"]-df["CustomerSince"].min())[0].days

1079

In [27]:
min_time=df["CustomerSince"].min()
def to_days(x):
    return (x-min_time).days
df["CustomerSince"]=df["CustomerSince"].map(to_days)

In [28]:
df

Age  CustomerSince  SupportCallsLastYear  AverageBill  ChurnIndicator  \
0       1           1079                     1           71               0   
1      46            469                     0           88               0   
2      47            762                     1           80               0   
3      43             69                     1           64               0   
4      37            396                     2          105               0   
...   ...            ...                   ...          ...             ...   
9985   39            226                     5           76               0   
9986   55            424                     1           86               0   
9987   37            623                     2           68               0   
9988   22            449                     0           53               0   
9989   79            229                     4           86               0   

      Technology_4G  Technology_fiber  Technology_landline  Technology_phone  
0                 1                 0                    0                 0  
1                 0                 0                    0                 1  
2                 1                 0                    0                 0  
3                 0                 0                    0                 1  
4                 0                 1                    0                 0  
...             ...               ...                  ...               ...  
9985              0                 1                    0                 0  
9986              0                 0                    0                 1  
9987              1                 0                    0                 0  
9988              0                 0                    1                 0  
9989              0                 0                    0                 1  

[9990 rows x 9 columns]

In [29]:
x=df[['Age', 'CustomerSince', 'SupportCallsLastYear', 'AverageBill','Technology_4G', 'Technology_fiber',
       'Technology_landline', 'Technology_phone']].values
y=df['ChurnIndicator'].values

In [30]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
model=RandomForestClassifier(n_estimators=10,max_depth=2, random_state=1234)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
f1_score(y_test, y_pred)

0.0

In [56]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
model=RandomForestClassifier(n_estimators=10,max_depth=2, random_state=1234,class_weight='balanced')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
f1_score(y_test, y_pred)

0.15873015873015872